type = "card"
layout = "list"
title = "Service"
hide_title = true

[[items]]
section = "Journal Service"
title = "Young Editorial Board Member"
content = "Young Editorial Board member, *The Innovation Energy Use*."

[[items]]
section = "Journal Service"
title = "Guest Editor"
content = "Guest editor for *Energy*, *Building Simulation*, *Buildings*, *Architecture*, *Journal of Physics: Conference Series*, and *Journal of Building Design and Environment*."

[[items]]
section = "Journal Service"
title = "Peer Reviewer"
content = "Reviewer for *Building Simulation*, *Applied Energy*, *Engineering*, *Energy Conversion and Management*, *Energy*, *Energy and Buildings*, *Energy Policy*, *Journal of Energy Storage*, *Sustainable Energy, Grids and Networks*, *HKIE Transactions*, and other SCI journals."

[[items]]
section = "Conference Service"
title = "Scientific Secretary"
subtitle = "The First International Conference on Digital Intelligence for Energy Systems"
date = "2025"
content = "Scientific secretary for ICDIES, Hong Kong, China."

[[items]]
section = "Conference Service"
title = "Technical Publication Committee Member"
subtitle = "IEEE 7th Student Conference on Electric Machines and Systems"
date = "2025"
content = "Technical publication committee member for IEEE SCEMS, Macau, China."

[[items]]
section = "Conference Service"
title = "Session Chair"
subtitle = "CUE2025-Applied Energy Symposium and Forum"
date = "2025"
content = "Session chair for CUE2025 in Kitakyushu, Japan."

[[items]]
section = "Research Projects"
title = "Large-scale Flexible Control and Supply-demand Coordinated Optimization of Integrated Energy Systems towards Carbon Neutrality"
subtitle = "The Hong Kong Polytechnic University Start-up Fund"
date = "2025-2027"
content = "Principal investigator. Funding: HK$300,000."

[[items]]
section = "Research Projects"
title = "Study on systematic quantification method, design and control optimization of energy-efficient and grid-responsive buildings"
subtitle = "The Hong Kong Polytechnic University Postdoc Matching Fund Scheme"
date = "2023-2025"
content = "Principal investigator. Funding: HK$365,000."

[[items]]
section = "Research Projects"
title = "Model-data hybrid rapid evaluation method for building energy flexibility"
subtitle = "China Southern Power Grid"
date = "2024-2026"
content = "Key researcher. Funding: RMB 2.3867 million."

[[items]]
section = "Research Projects"
title = "Research and demonstration of high-efficiency building energy-saving and power flexibility technologies"
subtitle = "Shenzhen Science and Technology Innovation Commission"
date = "2023-2025"
content = "Key researcher. Funding: RMB 5.10 million."
