type = "card"
layout = "list"
title = "Invited Talks"

[[items]]
title = "Risk-aware optimization for resource aggregator in multi-layered markets"
subtitle = "The 11th Asia Conference on Power and Electrical Engineering"
date = "2026"
content = "April 2026, Macau, China. Best Presentation Award."

[[items]]
title = "Maximizing the value of building energy flexibility: from multi-layered market design to risk-aware optimization"
subtitle = "The 10th International Conference on Energy and Environmental Science"
date = "2026"
content = "March 2026, Shanghai, China."

[[items]]
title = "Stackelberg game-based interactive flexibility provision scheme for demand-side management"
subtitle = "The 14th International Conference on Renewable Power Generation"
date = "2025"
content = "October 2025, Shanghai, China."

[[items]]
title = "Chance-constrained dispatch optimization considering probabilistic prediction of renewable generation and interactive flexibility engagement of building"
subtitle = "CUE2025-Applied Energy Symposium and Forum"
date = "2025"
content = "July 2025, Kitakyushu, Japan."

[[items]]
title = "Flexible control and supply-demand coordinated optimization of building energy systems towards carbon neutrality"
subtitle = "The 13th Sustainable Development in the Building and Environment International Conference"
date = "2025"
content = "August 2025, Cambridge, United Kingdom."

[[items]]
title = "A flexibility engagement scheme for unlocking the building energy flexibility in electricity markets"
subtitle = "The 13th International Symposium on Heating, Ventilation and Air Conditioning"
date = "2023"
content = "November 2023, Beijing, China."

[[items]]
title = "Stackelberg game-based flexibility provision scheme for demand-side management"
subtitle = "The 11th Sustainable Development in the Building and Environment International Conference"
date = "2023"
content = "August 2023, Espoo, Finland."

[[items]]
title = "Energy efficient and flexible buildings to achieve low carbon development in high density cities"
subtitle = "APEC Energy Forum 2022 - Low Carbon and Green Campus Wisdom Action"
date = "2022"
content = "November 2022, Hong Kong SAR."

[[items]]
title = "Interactive scheme for demand-side management in electricity markets of multiple services"
subtitle = "The 14th International Conference on Applied Energy"
date = "2022"
content = "August 2022, Bochum, Germany."

[[items]]
title = "Optimal dispatch strategy for building aggregators to fully utilize the energy flexibilities"
subtitle = "The 14th REHVA HVAC World Congress Conference"
date = "2022"
content = "May 2022, Rotterdam, Netherlands."

[[items]]
title = "Study on the Optimization of PCM Integrated Air-Conditioning Duct for the Demand Shifting"
subtitle = "The 4th Asia Conference of International Building Performance Simulation Association"
date = "2018"
content = "December 2018, Hong Kong SAR."
