[[news]]
date = "2026-06"
tag = "报告"
content = "在 BAS 2026 香港科技大学 Workshop “Energy interaction between buildings and electric vehicles towards grid decarbonization”作邀请报告，地点为中国香港。"

[[news]]
date = "2026-06"
tag = "论文"
content = "论文“Incremental online learning with model augmentation for AI-enabled optimization of building cooling systems”被 Energy 接收。"

[[news]]
date = "2026-05"
tag = "论文"
content = "论文“Techno-economic analysis and life cycle design optimization of demand-side hybrid energy storage under different climates and electricity markets”被 Energy 接收。"

[[news]]
date = "2026-05"
tag = "论文"
content = "论文“AI-empowered online optimization adopting local energy gradient for robust and energy-efficient control of building cooling systems”被 Journal of Building Engineering 接收。"

[[news]]
date = "2026-04"
tag = "服务"
content = "受聘担任 The Innovation Energy Use 青年编委。"

[[news]]
date = "2026-04"
tag = "获奖"
content = "在 The 11th Asia Conference on Power and Electrical Engineering（中国澳门）获得最佳汇报奖。"

[[news]]
date = "2026-04"
tag = "报告"
content = "在 ACPEE 2026 作题为“Risk-aware optimization for resource aggregator in multi-layered markets”的报告，地点为中国澳门。"

[[news]]
date = "2026-04"
tag = "论文"
content = "论文“Multi-Timescale Rolling Optimization Coordinating Heterogeneous EV and Building Load Flexibility in Community Energy Systems with NGBoost-Based Renewable Forecast”被 Applied Energy 接收。"

[[news]]
date = "2026-03"
tag = "报告"
content = "在 ICEES 2026 作题为“Maximizing the value of building energy flexibility: from multi-layered market design to risk-aware optimization”的报告，地点为中国上海。"
