type = "card"
layout = "list"
title = "学术服务"
hide_title = true

[[items]]
section = "期刊服务"
title = "青年编委"
content = "担任 *The Innovation Energy Use* 与 *Building Simulation* 青年编委。"

[[items]]
section = "期刊服务"
title = "客座编辑"
content = "担任 *Energy*、*Building Simulation*、*Buildings*、*Architecture*、*Journal of Physics: Conference Series* 与 *Journal of Building Design and Environment* 客座编辑。"

[[items]]
section = "期刊服务"
title = "期刊审稿人"
content = "受邀担任 *Building Simulation*、*Applied Energy*、*Engineering*、*Energy Conversion and Management*、*Energy*、*Energy and Buildings*、*Energy Policy*、*Journal of Energy Storage*、*Sustainable Energy, Grids and Networks*、*HKIE Transactions* 等 SCI 期刊审稿人。"

[[items]]
section = "会议服务"
title = "科研秘书长"
subtitle = "The First International Conference on Digital Intelligence for Energy Systems"
date = "2025"
content = "担任 ICDIES 科研秘书长，地点为中国香港。"

[[items]]
section = "会议服务"
title = "技术出版委员会成员"
subtitle = "IEEE 7th Student Conference on Electric Machines and Systems"
date = "2025"
content = "担任 IEEE SCEMS 技术出版委员会成员，地点为中国澳门。"

[[items]]
section = "会议服务"
title = "分会场主席"
subtitle = "CUE2025-Applied Energy Symposium and Forum"
date = "2025"
content = "担任 CUE2025 分会场主席，地点为日本北九州。"

[[items]]
section = "科研项目"
title = "面向碳中和的大规模综合能源系统柔性控制与供需协同优化"
subtitle = "香港理工大学专项启动基金"
date = "2025-2027"
content = "主持。经费：30万港币。"

[[items]]
section = "科研项目"
title = "高效节能与电网友好建筑系统化量化、设计与控制优化研究"
subtitle = "香港理工大学博士后匹配基金计划"
date = "2023-2025"
content = "主持。经费：36.5万港币。"

[[items]]
section = "科研项目"
title = "面向工程化可实施需求的模型数据混合驱动的建筑能源柔性快速评估方法"
subtitle = "中国南方电网有限责任公司科技项目"
date = "2024-2026"
content = "主研。经费：238.67万元。"

[[items]]
section = "科研项目"
title = "建筑高效节能及电力柔性技术研究与应用示范"
subtitle = "深圳市科技创新委员会可持续发展专项项目"
date = "2023-2025"
content = "主研。经费：510万元。"
